# HWNASConfig that defines the HW-Nas Behavior.
# If parameters are not specified inside the config, they are set to default values.

HWNASConfig:
  # Processor type (cpu, cuda:n) of the host that the experiment should run on.
  host_processor: "cuda" 

  # The search trials the HW-NAS should do at max.
  max_search_trials: 36

  # Whether to count only completed trials towards the max_search_trials OR to count all trials (including failed ones).
  count_only_completed_trials: false

  # The number of top models returned by HW-NAS.
  top_n_models: 1

  # The search algorithm to use for the HW-NAS.
  # Options: "random", "grid", "evolution"
  search_algorithm: "random"

  # The hardware constraints for the search.
  # Currently, only "max_flops" and "max_params" are supported.
  # Max. capabilities of Raspberry Pi platforms: RPi4 ~ 4.4 GFLOPS, RPi5 ~ 10 GFLOPS.
  hw_constraints: {
    "max_flops": 10e9 # 10 GFLOPS, model should not take longer than 1 second per inference on RPi5.
  #  "max_params": 1e6
  }

  # The number of training epochs for accuracy estimation.
  n_estimation_epochs: 5

  # The weight of the FLOPs-Estimation for the Proxy metric.
  # proxy_metric = accuracy_estimation - log10(flops_estimation) * flops_weight
  flops_weight: 0.0
