input: [90, 4]
output: 1
sequence:
  - block: "1"
    type_repeat:
      type: "repeat_op"
      depth: [1]
    op_candidates: ["lstm"]
    lstm:
      hidden_size: [10, 15, 20, 25]
      num_layers: [1, 2, 3]
      bidirectional: [False]
      dropout: [0.0, 0.2, 0.4]
  - block: "2"
    op_candidates: ["linear"]
    type_repeat:
      type: "repeat_op"
      depth: [1]
    linear:
      activation: ["identity"]
      width: [10]
