# HWNASConfig that defines the HW-Nas Behavior.
# If parameters are not specified inside the config, they are set to default values.
HWNASConfig:
  #Processor type (cpu, cuda:n) of the host, the experiment should run on.
  host_processor: "auto" 

  # The search trials the HW-NAS should do at max.
  max_search_trials: 4


  # The number of top models returned by HW-NAS.
  top_n_models: 2

  # The number of training epochs for accuracy estimation.
  n_estimation_epochs: 2

  # The weight of the FLOPs-Estimation for the Proxymetric.
  # proxy_metric = accuracy_estimation - log10(flops_estimation) * flops_weight
  flops_weight: 2

